# Generated by Django 3.2.8 on 2022-07-10 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contragents', '0002_alter_contragent_street'),
        ('goods', '0009_auto_20220709_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique agreement code')),
                ('result', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Refused'), (3, 'In progress')], default=3, verbose_name='Agreement result')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited date')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contragents.contragent', verbose_name='Contragent')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited date')),
            ],
            options={
                'verbose_name': 'Task status',
                'verbose_name_plural': 'Task statuses',
            },
        ),
        migrations.CreateModel(
            name='AgreementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Task date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited date')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.agreement', verbose_name='Agreement')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.taskstatus', verbose_name='Agreement status')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='AgreementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.agreement', verbose_name='Agreement')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.pharmproduct', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Agreement item',
                'verbose_name_plural': 'Agreement items',
            },
        ),
    ]
